fix problems with a new back stack
Otus-GPB/activities_01 pull request #10
Opened 2022-08-30 15:56 UTC by Vojan-Najov

2022-09-03 11:02 UTC, antonkazakov requested changes
Привет. Пара замечаний

2022-09-03 11:02 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityB.kt
> +                .setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
А зачем здесь FLAG_ACTIVITY_NEW_TASK?

2022-09-03 11:02 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            startActivity(intent)
Не нужно стартовать Activity, finishAffinity должно быть достаточно. Ты закроешь текущий стек и вернешься к ActivityA

2022-09-03 11:02 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +                .setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
А зачем здесь флаги эти?

2022-09-03 11:51 UTC, Vojan-Najov commented on app/src/main/java/otus/gpb/homework/activities/ActivityB.kt
> +                .setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
Видимо пока я в манифесте для всех активити кроме А явно не прописал taskAffinity поведение не соответствовало моим ожиданиям. Это действительно, не обязательно

2022-09-03 11:53 UTC, Vojan-Najov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            startActivity(intent)
Сделал так, чтобы при закрытии стека, возвращаться явно к активити А, а не к тому, что потенциально может быть на верху стека с активити А.

2022-09-03 11:55 UTC, Vojan-Najov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +                .setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
при наличии launchMode == signleTask по идеи не обязательно. Насколько я понял если добавить флаги, то это перекрывает определение из манифеста. Таким образом, это одно и тоже, как мне показалось.

2022-09-18 15:37 UTC, antonkazakov reviewed
👍

2022-09-18 15:37 UTC, closed without merging