Homeworks/activities 01
Otus-GPB/activities_01 pull request #14
Opened 2022-08-31 04:49 UTC by Zanozaroom

2022-09-03 10:23 UTC, antonkazakov requested changes
Привет. Оставил несколько замечаний

2022-09-03 10:23 UTC, antonkazakov commented on app/src/main/AndroidManifest.xml
> +            android:taskAffinity="com.activity.personaltask">
У нее можно не указывать афинити

2022-09-03 10:23 UTC, antonkazakov commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleInstance"
Нужно убрать и переделать на singleTask

2022-09-03 10:23 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityA.kt
> +            val intent = Intent(this, ActivityB::class.java)
Здесь должен появиться флаг на новый таск

2022-09-03 10:23 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            onBackPressed()
Вызови finish

2022-09-03 10:23 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
А здесь разве нужен FLAG_ACTIVITY_NEW_TASK?

2022-09-03 11:43 UTC, Zanozaroom commented on app/src/main/java/otus/gpb/homework/activities/ActivityA.kt
> +            val intent = Intent(this, ActivityB::class.java)
Поставила флаг запуска в новом таске

2022-09-03 11:44 UTC, Zanozaroom commented on app/src/main/AndroidManifest.xml
> +            android:taskAffinity="com.activity.personaltask">
Решила указать, чтобы "красиво" было ) Все активити с именованными тасками) Убрала )

2022-09-03 11:50 UTC, Zanozaroom commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
Согласна, перебор. Лишняя перестраховка была)

2022-09-03 11:51 UTC, Zanozaroom commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            onBackPressed()
Сделано.

2022-09-03 11:51 UTC, Zanozaroom commented on app/src/main/java/otus/gpb/homework/activities/ActivityA.kt
> +            val intent = Intent(this, ActivityB::class.java)
Сделано

2022-09-18 15:34 UTC, antonkazakov requested changes
Привет. Оставил два небольших замечания, посмотри пожалуйста

2022-09-18 15:34 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)
А здесь не нужен разве флаг NEW_TASK еще?

2022-09-19 06:44 UTC, Zanozaroom commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)
Я так понимаю, он не нужен, если в манифесте singleTask стоит. У меня он удалял при запуске все другие активити в стеке. После того, как удалила в манифесте лаунчмод, то пришлось добавить NEW_TASK  в флаг интента.

2022-09-19 06:45 UTC, Zanozaroom commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleTask"
Поправила. Прости, что немного вышла за рамки задания)

2022-09-26 17:50 UTC, antonkazakov commented
Отлично :)

2022-09-26 17:50 UTC, closed without merging

2022-09-26 18:42 UTC, antonkazakov commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleTask"
А здесь зачем singleTask?