Решение ДЗ (Activities #1)
Otus-GPB/activities_01 pull request #19
Opened 2022-08-31 20:00 UTC by alexvsw

Решение ДЗ-1

2022-09-03 10:20 UTC, antonkazakov requested changes
Привет. Оставил пару замечаний, поправь плз

2022-09-03 10:20 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            val intent = Intent(this, ActivityA::class.java)
А зачем ты стартуешь ее? Разве после убийства стека ты на не ней окажешься?

2022-09-03 11:20 UTC, alexvsw commented on app/src/main/java/otus/gpb/homework/activities/ActivityA.kt
> +                .setFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP)
Допустим, у нас был переход по следующим activity: А->B->C->А. 
Теперь, если нажать кнопку "Open activity B", откроется активити С. 
Наверное это все таки неправильно?

2022-09-03 11:21 UTC, alexvsw commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            val intent = Intent(this, ActivityA::class.java)
Согласен, не внимательно посмотрел этот момент

2022-09-03 11:50 UTC, alexvsw commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +                .setFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)
Но, разве в нашем случае использование что того, что другого флага не приведет к одинаковому поведению?

2022-09-03 11:51 UTC, alexvsw commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +                .setFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)
Увидел, что нужно было еще использовать FLAG_ACTIVITY_NEW_TASK)

2022-10-22 06:54 UTC, antonkazakov reviewed
👍

2022-10-22 06:55 UTC, closed without merging