Homeworks/activities 01
Otus-GPB/activities_01 pull request #21
Opened 2022-09-01 12:12 UTC by taasonei

2022-09-03 10:28 UTC, antonkazakov requested changes
Привет. Поправь пожалуйста вызов диспатчера на finish. В твоей реализации все правильно работает, но вполне может быть ситуация что диспатчер или onBackPressed будут вести себя по другому и не дублировать поведение finish

2022-09-03 10:28 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            onBackPressedDispatcher.onBackPressed()
Здесь вызови finish

2022-09-05 10:11 UTC, taasonei commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            onBackPressedDispatcher.onBackPressed()
А здесь разве мы не попадем в коллбэке в
`override fun handleOnBackPressed() {
                    if (isEnabled) {
                        finish()
                    }`
и как раз будет вызов finish?

2022-09-15 15:55 UTC, taasonei commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            onBackPressedDispatcher.onBackPressed()
Исправила на вызов finish()

2022-11-05 20:41 UTC, antonkazakov commented
👍

2022-11-05 20:41 UTC, closed without merging