Homework/activities 02
Otus-GPB/activities_01 pull request #27
Opened 2022-09-02 04:12 UTC by Zanozaroom

2022-09-11 18:47 UTC, antonkazakov requested changes
Привет. Несколько небольших замечаний оставил по коду, по самим заданиям все ок

2022-09-11 18:47 UTC, antonkazakov commented on sender/src/main/java/otus/gpb/homework/activities/sender/SenderActivity.kt
> +        } catch (e: Exception) {
Я думаю правильнее все-таки ловить `ActivityNotFoundException`, сейчас у тебя впринципе может упасть другой, но в тосте ты покажешь информацию о том что нет активити

2022-09-11 18:47 UTC, antonkazakov commented on sender/src/main/java/otus/gpb/homework/activities/sender/SenderActivity.kt
> +        val payloadIntent = Intent(Intent.ACTION_SEND).apply {
Можно и без apply, это билдер методы которые возвращают Intent, а не Unit

2022-09-11 18:47 UTC, antonkazakov commented on sender/src/main/java/otus/gpb/homework/activities/sender/SenderActivity.kt
> +        } catch (e: Exception) {
Тоже самое

2022-09-11 18:47 UTC, antonkazakov commented on receiver/src/main/java/otus/gpb/homework/activities/receiver/ReceiverActivity.kt
> +        val KEY_PAYT="Title"
А эти константы еще где-то используются? Почему не приватные?

2022-09-11 18:47 UTC, antonkazakov commented on receiver/src/main/java/otus/gpb/homework/activities/receiver/ReceiverActivity.kt
> +        val intent:HashMap<String,String> = getIntent().getSerializableExtra(Intent.EXTRA_TEXT) as HashMap<String, String>
Мне кажется проще 3 строки передать)

2022-09-12 03:21 UTC, Zanozaroom commented on sender/src/main/java/otus/gpb/homework/activities/sender/SenderActivity.kt
> +        val payloadIntent = Intent(Intent.ACTION_SEND).apply {
Так не надо постоянно писать "payloadIntent. " :) Поэтому выбрала этот вариант, в интент много складывать надо )

2022-09-12 03:23 UTC, Zanozaroom commented on sender/src/main/java/otus/gpb/homework/activities/sender/SenderActivity.kt
> +        val payloadIntent = Intent(Intent.ACTION_SEND).apply {
Просто до этого в интент складывала в блоке apply, решила оставить и в этом интенте этот блок, чтобы код был одинаковым по структуре. Пусть будет?

2022-09-12 03:23 UTC, Zanozaroom commented on sender/src/main/java/otus/gpb/homework/activities/sender/SenderActivity.kt
> +        } catch (e: Exception) {
Поменяла

2022-09-12 03:23 UTC, Zanozaroom commented on sender/src/main/java/otus/gpb/homework/activities/sender/SenderActivity.kt
> +        } catch (e: Exception) {
Полностью согласна, поменяла.

2022-09-12 03:26 UTC, Zanozaroom commented on receiver/src/main/java/otus/gpb/homework/activities/receiver/ReceiverActivity.kt
> +        val KEY_PAYT="Title"
Не оставляла попытки связать два модуля ) Думала после обращаться к константам через имя класса, но ничего в итоге не получилось. Знаний недостаточно... Запарилась и забыла указать их как приватные, когда уже дописала код без связки модулей. Поправила. Константы используются только в этом классе

2022-09-12 03:34 UTC, Zanozaroom commented on receiver/src/main/java/otus/gpb/homework/activities/receiver/ReceiverActivity.kt
> +        val intent:HashMap<String,String> = getIntent().getSerializableExtra(Intent.EXTRA_TEXT) as HashMap<String, String>
Проще, но был выбран hashmap по двум причинам:
1) Хотелось передать через интерфейс :)
2) Мне кажется, так мы исключаем возможную ошибку на стороне второй активити - в мапе  есть ключи и через них мы вытягиваем текст для вьюх, а не через ключи интентов. В то время, как сам интент содержит стандартный флаг передачи текста.

2022-09-26 17:53 UTC, antonkazakov commented on receiver/src/main/java/otus/gpb/homework/activities/receiver/ReceiverActivity.kt
> +        val intent:HashMap<String,String> = getIntent().getSerializableExtra(Intent.EXTRA_TEXT) as HashMap<String, String>
А разве я не могу ошибиться в запросе значения по ключу?

В целом я настаивать не буду, но я думаю что и с точки зрения перфоманса(сериализация - десериализация, доступ к элементам в ассоциативном массиве), и с точки зрения читаемости положить 3 строки гораздо проще)

2022-09-26 17:53 UTC, closed without merging