Homeworks/activities 01
Otus-GPB/activities_01 pull request #30
Opened 2022-09-03 10:42 UTC by by-westik

2022-09-03 10:59 UTC, antonkazakov requested changes
Привет. Оставил два маленьких замечания

2022-09-03 10:59 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            startActivity(Intent(this, ActivityA::class.java))
А зачем ее стартовать? У тебя же есть стек очиститься ты сама туда перейдешь

2022-09-03 10:59 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            super.onBackPressed()
Поменяй плз на finish

2022-09-03 20:12 UTC, by-westik commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            startActivity(Intent(this, ActivityA::class.java))
Я думала, что нужно явно указывать переход на другую Activity

2022-09-03 20:12 UTC, by-westik commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            super.onBackPressed()
Готово

2022-09-18 15:42 UTC, antonkazakov reviewed
👍

2022-09-18 15:42 UTC, closed without merging