Решение второго ДЗ
Otus-GPB/activities_01 pull request #31
Opened 2022-09-03 13:10 UTC by coolkosta

2022-09-18 16:07 UTC, antonkazakov requested changes

2022-09-18 16:07 UTC, antonkazakov commented on receiver/src/main/java/otus/gpb/homework/activities/receiver/ReceiverActivity.kt
> +        const val EXTRA_TITLE = "title"
А зачем тебе константы, тем более глобальные, если они все равно не переиспользуются нигде?

2022-09-18 16:07 UTC, antonkazakov commented on sender/src/main/java/otus/gpb/homework/activities/sender/SenderActivity.kt
> +            val intent = Intent(Intent.ACTION_VIEW, mapUriIntent)
А это же неявный интент у тебя, нужен явный на Гугл Мапс

2022-09-18 16:07 UTC, antonkazakov commented on sender/src/main/java/otus/gpb/homework/activities/sender/SenderActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
Очень большая функция получилась, разбей ее на насколько

2022-09-18 16:07 UTC, antonkazakov commented on sender/src/main/java/otus/gpb/homework/activities/sender/SenderActivity.kt
> +    private fun createExtra(a: Movie, b: Movie) : Movie {
a b довольно странные названия параметров. Сделай чтобы эта функция без входных параметров по Random выбирала какой Movie создать

2022-09-20 11:34 UTC, coolkosta commented on receiver/src/main/java/otus/gpb/homework/activities/receiver/ReceiverActivity.kt
> +        const val EXTRA_TITLE = "title"
Мы же данные получаем по ключу, поэтому прописал константы. Сделал их приватными

2022-09-26 18:18 UTC, antonkazakov commented on receiver/src/main/java/otus/gpb/homework/activities/receiver/ReceiverActivity.kt
> +        const val EXTRA_TITLE = "title"
Ну имхо эти константы никакой проблемы не решают. Удобно если ты их используешь в нескольких местах, а так абсолютно столько же кода)

2022-09-26 18:25 UTC, antonkazakov commented
👍

2022-09-26 18:25 UTC, closed without merging