Homework/activity 03
Otus-GPB/activities_01 pull request #42
Opened 2022-09-12 10:07 UTC by alexvsw

Решение ДЗ-3 (Activity #3)

2022-10-02 15:38 UTC, antonkazakov requested changes
Привет. Оставил несколько замечаний, еще у тебя падает detekt, нужно поправить его и мои замечания

2022-10-02 15:38 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/FillFormActivity.kt
> +        val name = findViewById<EditText>(R.id.editTextPersonName).text.toString()
Я думаю биндинг вью лучше перенести в onCreate

2022-10-02 15:38 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +        const val TYPE_IMAGE = "image/*"
Их можно сделать private, но я бы вообще не делал их константами. Они нигде не переиспользуются и это не magic numbers

2022-10-02 15:38 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +        if(intent.resolveActivity(packageManager) == null) {
С 31 версии нужно декларировать в Манифесте про какие пакеты ты хочешь узнавать https://developer.android.com/training/package-visibility

2022-10-02 15:38 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +        imageView.drawable
Нужно убрать

2022-10-07 18:56 UTC, alexvsw commented
Поправил замечания

2022-10-22 06:58 UTC, antonkazakov commented
👍

2022-10-22 06:58 UTC, closed without merging