Homework/activity 03
Otus-GPB/activities_01 pull request #45
Opened 2022-09-12 17:53 UTC by LanaLebedeva

Пожалуйста, посмотрите задание  Activity#3

2022-10-02 16:02 UTC, antonkazakov requested changes
Привет!
1. Поправь, пожалуйста, мои замечания
2. Поправь ошибки которые нашел detekt

2022-10-02 16:02 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +        val sendIntent = Intent().apply {
Здесь нет интента на Телеграм

2022-10-02 16:02 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +        findViewById<ImageView>(R.id.imageview_photo).setOnClickListener { takePhoto() }
Логика работы с запросом пермишеном не соответствует условиям задания

2022-10-03 10:26 UTC, LanaLebedeva commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +        findViewById<ImageView>(R.id.imageview_photo).setOnClickListener { takePhoto() }
Не поняла замечания - на мой взгляд все работает в соответствии с заданием.

2022-10-03 10:29 UTC, LanaLebedeva commented
Не смогла запустить detect 
![Снимок экрана от 2022-10-03 13-28-06](https://user-images.githubusercontent.com/58044657/193556484-76c389c1-2159-4614-87e1-d0a68145e900.png)

2022-10-03 10:31 UTC, LanaLebedeva commented on app/src/main/AndroidManifest.xml
> +            <meta-data
Ok

2022-10-03 10:31 UTC, LanaLebedeva commented on app/src/main/java/otus/gpb/homework/activities/FillFormActivity.kt
> +        const val NAME = "name_from_fill_form"
ok

2022-10-03 10:31 UTC, LanaLebedeva commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +        val sendIntent = Intent().apply {
Ok

2022-10-16 08:53 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +        findViewById<ImageView>(R.id.imageview_photo).setOnClickListener { takePhoto() }
Нет редиректа в настройки после того как 2 раза отказал в пермишене

2022-11-05 20:37 UTC, antonkazakov commented
👍

2022-11-05 20:37 UTC, closed without merging