Homework/activity 03
Otus-GPB/activities_01 pull request #46
Opened 2022-09-12 19:58 UTC by pashabezborod

2022-10-02 15:50 UTC, antonkazakov requested changes
Привет.
1. Поправь, пожалуйста, мои замечания
2. Доделай отправку изображения в интент
3. Поправь ошибки detekt'a

2022-10-02 15:50 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +    private lateinit var bitmap: Bitmap
А зачем эта переменная?

2022-10-02 15:50 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +//            .putExtra("Img", imageView.drawable.toBitmap())
Почитай https://guides.codepath.com/android/Sharing-Content-with-Intents

2022-10-02 15:50 UTC, antonkazakov commented on app/src/main/res/layout/activity_fill_from.xml
> +        android:text="AGE"
Я думаю это нужно перенести в hint, иначе сейчас придется стирать текст а потом вводить новый

2022-10-18 17:03 UTC, pashabezborod commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +    private lateinit var bitmap: Bitmap
Искал способы загрузить файл в интент, это был временный вариант, забыл удалить

2022-10-18 17:03 UTC, pashabezborod commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +//            .putExtra("Img", imageView.drawable.toBitmap())
Сдклал, всё получилось, спасибо большое)

2022-10-18 17:05 UTC, pashabezborod commented on app/src/main/res/layout/activity_fill_from.xml
> +        android:text="AGE"
Это на самом деле тоже использовал для проверки, чтобы не вводить текст каждый раз, но спасибо, что заметили)

2022-11-06 13:29 UTC, antonkazakov commented
👍

2022-11-06 13:29 UTC, closed without merging