дз номер 1
Otus-GPB/activities_01 pull request #48
Opened 2022-09-12 22:16 UTC by AgnaWiese

Сделала домашнее задание по лекции Activity #1

2022-09-26 19:05 UTC, antonkazakov requested changes
Привет. Оставил замечания, нужно поправить

2022-09-26 19:05 UTC, antonkazakov commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleInstance">
Сингл инстанс не подойдет, здесь всегда размер стека в котором лежит ActivityA = 1

2022-09-26 19:05 UTC, antonkazakov commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleTask" />
Зачем здесь singleTask?

2022-09-26 19:05 UTC, antonkazakov commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleTask" />
И здесь

2022-09-26 19:05 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityA.kt
> +            startActivity(Intent(this, ActivityB::class.java))
Нужно ее запустить в новом таске, необходим флаг

2022-09-26 19:05 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            intent.flags = Intent.FLAG_ACTIVITY_CLEAR_TASK
Нужен флаг чтобы запустить в новом таске

2022-09-27 07:08 UTC, AgnaWiese commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleInstance">
Здесь и далее экспериментировала: 
1) singleInstance был, чтобы ActivityB открывался в новом стэке без указания флага "Intent.FLAG_ACTIVITY_NEW_TASK" и чтобы для вызова finishAffinity() не приходилось в ActivityB, ActivityС и ActivityD вручную прописывать affinity в манифесте
2) обошлась без флагов Intent.FLAG_ACTIVITY_NEW_TASK для открытия активностей, так как в манифесте везде прописывала android:launchMode="singleTask"

После экспериментов оставила такой вариант, так как он работает также, но меньше кода :)

В любом случае, в новом кормите вернула везде ручное задание  Intent.FLAG_ACTIVITY_NEW_TASK в интентах, прописала вручную affinity в манифесте и убрала android:launchMode="singleTask", где теперь не нужно :)

2022-09-28 18:27 UTC, antonkazakov commented
👍

2022-09-28 18:27 UTC, closed without merging