Homework/activity 03
Otus-GPB/activities_01 pull request #52
Opened 2022-09-17 16:27 UTC by taasonei

2022-10-02 17:14 UTC, antonkazakov requested changes
Привет. Поправь, пожалуйста, ошибки detekt

2022-10-02 17:14 UTC, antonkazakov commented on gradle.properties
> +android.enableJetifier=true
А зачем тебе джетифаер?

2022-10-02 17:14 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/IntentUtils.kt
> +    const val NAME = "name"
Я бы на твоем месте эти константы просто привязал к одному из активити, лучше к тому который стартует интент

2022-10-31 18:33 UTC, taasonei commented on gradle.properties
> +android.enableJetifier=true
У меня почему-то без него проект не билдился. Убрала, сейчас билдится

2022-10-31 18:48 UTC, taasonei commented on app/src/main/java/otus/gpb/homework/activities/IntentUtils.kt
> +    const val NAME = "name"
Сделано, привязала к EditProfileActivity

2022-11-05 20:41 UTC, antonkazakov commented
👍

2022-11-05 20:41 UTC, closed without merging