Homework 03
Otus-GPB/activities_01 pull request #62
Opened 2022-10-02 20:20 UTC by Kaizer22

2022-11-05 20:05 UTC, antonkazakov requested changes
Привет. Поправь, пожалуйста, замечания

2022-11-05 20:05 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +            findViewById<TextView>(R.id.edit_profile_name).text = profile.name
Это неправильный подход, каждый раз при срабатывании этого коллбека биндить вьюхи, забинди их и переиспользуй

2022-11-05 20:05 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/EditProfileActivity.kt
> +        startActivity(telegramIntent)
Добавь, пожалуйста, обработку кейса когда на девайсе нет Телеграма, сейчас будет краш, я думаю правильнее просто показать какое то сообщение

2022-11-05 20:05 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/FillFormActivity.kt
> +            surname = findViewById<EditText>(R.id.fill_form_surname).text.toString(),
Аналогично

2022-11-06 12:58 UTC, Kaizer22 commented
Исправил. Еще добавил пересылку дефолтной картинки в Telegram, но столкнулся с проблемой, что Uri для картинки из resources Telegram не понимает и выдает "Вложение не поддерживается". Попробовал проставить в Uri тип "content" (сейчас так), но не помогло

2022-11-20 09:46 UTC, antonkazakov commented
👍

2022-11-20 09:46 UTC, closed without merging