Activity#1 Homework
Otus-GPB/activities_01 pull request #7
Opened 2022-08-29 17:21 UTC by mbelyakov

2022-09-03 09:04 UTC, antonkazakov requested changes
Привет. Поправь, пожалуйста, замечания

2022-09-03 09:04 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            finishAffinity()
Реши это пожалуйста через флаги, не меняя поведение ActivityA в манифесте

2022-09-03 09:04 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityA.kt
> +            val intent = Intent(this, ActivityB::class.java)
Разве она в отдельном таске открывается?

2022-09-03 09:04 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityB.kt
> +            val intent = Intent(this, ActivityC::class.java)
Нужно открыть в том же таске где B, А должна быть в другом

2022-09-05 04:20 UTC, mbelyakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityC.kt
> +            finishAffinity()
Переделал

2022-09-18 16:08 UTC, antonkazakov reviewed
Привет. Работу засчитываю, но флаг `FLAG_ACTIVITY_CLEAR_TOP` в `ActivityA` тебе не нужен

2022-09-18 16:08 UTC, antonkazakov commented on app/src/main/java/otus/gpb/homework/activities/ActivityA.kt
> +            intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP
А зачем тебе FLAG_ACTIVITY_CLEAR_TOP?

2022-09-18 16:09 UTC, closed without merging